// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PluralSightCoreDemo.Data;
using PluralSightCoreDemo.Models;
using System;

namespace PluralSightCoreDemo.Migrations
{
    [DbContext(typeof(PluralSightDemoDbContext))]
    [Migration("20180209093117_ImagesAdded")]
    partial class ImagesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PluralSightCoreDemo.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Population");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("PluralSightCoreDemo.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("ImageData");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PluralSightCoreDemo.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("TypeRestaurant");

                    b.HasKey("Id");

                    b.ToTable("Restourants");
                });

            modelBuilder.Entity("PluralSightCoreDemo.Models.RestaurantCity", b =>
                {
                    b.Property<int>("CityId");

                    b.Property<int>("ReataurantId");

                    b.HasKey("CityId", "ReataurantId");

                    b.HasIndex("ReataurantId");

                    b.ToTable("RestaurantCity");
                });

            modelBuilder.Entity("PluralSightCoreDemo.Models.RestaurantCity", b =>
                {
                    b.HasOne("PluralSightCoreDemo.Models.City", "CityData")
                        .WithMany("Restaurants")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PluralSightCoreDemo.Models.Restaurant", "RestaurantData")
                        .WithMany("Cities")
                        .HasForeignKey("ReataurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
